# Generated by Django 4.1.3 on 2022-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(verbose_name='Страна')),
                ('languages', models.TextField(verbose_name='Языки')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
